# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{deep_merge}
  s.version = "0.0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mathias Meyer, Jonathan Weiss"]
  s.date = %q{2010-09-28}
  s.description = %q{A fork of http://rubyforge.org/projects/deepmerge/ with 1.9 fixes and ActiveSupport compatability}
  s.email = %q{info@peritor.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/deep_merge.rb"
  ]
  s.homepage = %q{http://github.com/peritor/deep_merge}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A fork of http://rubyforge.org/projects/deepmerge/ with 1.9 fixes and ActiveSupport compatability}
  s.test_files = [
    "test/test_deep_merge.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

